config/routes.rb
Rails.application.routes.draw do
  resources :ikeja_services

  resources :ikeja_patients

  resources :nationalities

  resources :religions

  resources :occupations

  resources :lgas

  resources :states

  resources :branches

  get 'pages/index'

  root 'pages#index'
end

app/models/branch.rb
class Branch < ActiveRecord::Base
	validates :name, :address, :prefix, :suffix, presence: true
	validates :name, :address, uniqueness: true
	has_many :patients
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :services
end

app/models/ikeja_patient.rb
class IkejaPatient < ActiveRecord::Base
	acts_as :patient
end

app/models/ikeja_service.rb
class IkejaService < ActiveRecord::Base
	acts_as :service
end

app/models/lga.rb
class Lga < ActiveRecord::Base
  belongs_to :state
end

app/models/nationality.rb
class Nationality < ActiveRecord::Base
end

app/models/occupation.rb
class Occupation < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	after_create :set_mrn
	actable
	belongs_to :state
	belongs_to :branch
	belongs_to :lga
	belongs_to :religion
	belongs_to :occupation
	belongs_to :nationality
	Gender = %w(Female Male)
	validates :surname, :first_name, :address, :gender, :phone, :state, presence: true

	def set_mrn
		prefix = self.branch.prefix
		suffix = self.branch.suffix
		update_attribute(:mrn, "#{prefix}"+"#{self.id}"+"#{suffix}")
	end

	def fullName
		self.first_name+" "+self.middle_name+" "+self.surname
	end
end

app/models/religion.rb
class Religion < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
	actable
	validates :item, :amount, :category_id, presence: true
	validates :item, uniqueness: true
	belongs_to :category
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/controllers/ikeja_patients_controller.rb
class IkejaPatientsController < ApplicationController
  before_action :set_ikeja_patient, only: [:show, :edit, :update, :destroy]

  # GET /ikeja_patients
  # GET /ikeja_patients.json
  def index
    @ikeja_patients = IkejaPatient.all
  end

  # GET /ikeja_patients/1
  # GET /ikeja_patients/1.json
  def show
  end

  # GET /ikeja_patients/new
  def new
    @ikeja_patient = IkejaPatient.new
  end

  # GET /ikeja_patients/1/edit
  def edit
  end

  # POST /ikeja_patients
  # POST /ikeja_patients.json
  def create
    @ikeja_patient = IkejaPatient.new(ikeja_patient_params)

    respond_to do |format|
      if @ikeja_patient.save
        format.html { redirect_to ikeja_patients_path, notice: 'Ikeja patient was successfully created.' }
        format.json { render :index, status: :created, location: ikeja_patients_path }
      else
        format.html { render :new }
        format.json { render json: @ikeja_patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ikeja_patients/1
  # PATCH/PUT /ikeja_patients/1.json
  def update
    respond_to do |format|
      if @ikeja_patient.update(ikeja_patient_params)
        format.html { redirect_to @ikeja_patient, notice: 'Ikeja patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ikeja_patient }
      else
        format.html { render :edit }
        format.json { render json: @ikeja_patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ikeja_patients/1
  # DELETE /ikeja_patients/1.json
  def destroy
    @ikeja_patient.destroy
    respond_to do |format|
      format.html { redirect_to ikeja_patients_url, notice: 'Ikeja patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ikeja_patient
      @ikeja_patient = IkejaPatient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ikeja_patient_params
      params.require(:ikeja_patient).permit(:branch_id, :mrn, :surname, :first_name, :middle_name, :gender, :dob, :next_of_kin, :next_of_kin_phone, :state_id, :religion_id, :nationality_id, :occupation_id, :lga_id, :phone, :email, :address)
    end
end

app/controllers/lgas_controller.rb
class LgasController < ApplicationController
  before_action :set_lga, only: [:show, :edit, :update, :destroy]

  # GET /lgas
  # GET /lgas.json
  def index
    @lgas = Lga.all
  end

  # GET /lgas/1
  # GET /lgas/1.json
  def show
  end

  # GET /lgas/new
  def new
    @lga = Lga.new
  end

  # GET /lgas/1/edit
  def edit
  end

  # POST /lgas
  # POST /lgas.json
  def create
    @lga = Lga.new(lga_params)

    respond_to do |format|
      if @lga.save
        format.html { redirect_to @lga, notice: 'Lga was successfully created.' }
        format.json { render :show, status: :created, location: @lga }
      else
        format.html { render :new }
        format.json { render json: @lga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lgas/1
  # PATCH/PUT /lgas/1.json
  def update
    respond_to do |format|
      if @lga.update(lga_params)
        format.html { redirect_to @lga, notice: 'Lga was successfully updated.' }
        format.json { render :show, status: :ok, location: @lga }
      else
        format.html { render :edit }
        format.json { render json: @lga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lgas/1
  # DELETE /lgas/1.json
  def destroy
    @lga.destroy
    respond_to do |format|
      format.html { redirect_to lgas_url, notice: 'Lga was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lga
      @lga = Lga.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lga_params
      params.require(:lga).permit(:name, :state_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/ikeja_patients_helper.rb
module IkejaPatientsHelper
end

app/helpers/lgas_helper.rb
module LgasHelper
end

app/helpers/nationalities_helper.rb
module NationalitiesHelper
end

app/helpers/occupations_helper.rb
module OccupationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/religions_helper.rb
module ReligionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/ikeja_patients/_form.html.erb
<%= form_for(@ikeja_patient) do |f| %>
  <% if @ikeja_patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ikeja_patient.errors.count, "error") %> prohibited this ikeja_patient from being saved:</h2>

      <ul>
      <% @ikeja_patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-inline">
    <%= f.text_field :surname, placeholder: "Surname", class: "form-control" %>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
    <%= f.text_field :middle_name, placeholder: "Middle Name", class: "form-control" %>
  </div> <br>

    <div class="form-inline">
    <%= f.text_field :address, placeholder: "Address", class: "form-control" %>
    <%= f.phone_field :phone, placeholder: "Phone", class: "form-control" %>
    <%= f.email_field :email, placeholder: "Email", class: "form-control" %>
  </div> <br>
  <div class="form-inline">
    <%= f.select :gender, options_for_select(Patient::Gender, @ikeja_patient.gender), {prompt: 'Gender'}, {class: "form-control"} %>
    <%= f.collection_select :occupation_id, Occupation.all, :id, :name, {prompt: "Occupation"}, {class: "form-control"} %>
    <%= f.collection_select :religion_id, Religion.all, :id, :name, {prompt: "Religion"}, {class: "form-control"} %>
  </div> <br>
  <div class="form-inline">
    <%= f.collection_select :state_id, State.all, :id, :name, {prompt: "State of Residence"}, {class: "form-control"} %>
    <%= f.collection_select :lga_id, Lga.all, :id, :name, {prompt: "Local Govt"}, {class: "form-control"} %>
    <%= f.collection_select :nationality_id, Nationality.all, :id, :name, {prompt: "Nationality"}, {class: "form-control"} %>
  </div> <br>
  <div class="form-inline">
    <%= f.text_field :next_of_kin, placeholder: "Next of Kin", class: "form-control" %>
    <%= f.text_field :next_of_kin_phone, placeholder: "Next of Kin's phone", class: "form-control" %>
    <%= f.collection_select :branch_id, Branch.all, :id, :name, {prompt: "Select Branch"}, {class: "form-control"} %>
  </div> <br>
  <div class="form-group">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/ikeja_patients/edit.html.erb
<h1>Editing Ikeja Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ikeja_patient %> |
<%= link_to 'Back', ikeja_patients_path %>

app/views/ikeja_patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ikeja Patients</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>MR No.</th>
      <th>Registered?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ikeja_patients.each do |ikeja_patient| %>
      <tr>
        <td><%= ikeja_patient.fullName %></td>
        <td><%= ikeja_patient.mrn %></td>
        <td><%= ikeja_patient.registered %></td>
        <td><%= link_to 'Show', ikeja_patient %></td>
        <td><%= link_to 'Edit', edit_ikeja_patient_path(ikeja_patient) %></td>
        <td><%= link_to 'Destroy', ikeja_patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ikeja patient', new_ikeja_patient_path %>

app/views/ikeja_patients/new.html.erb
<h1>New Ikeja Patient</h1>
<hr>
<%= render 'form' %>

<%= link_to 'Back', ikeja_patients_path %>

app/views/ikeja_patients/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ikeja_patient_path(@ikeja_patient) %> |
<%= link_to 'Back', ikeja_patients_path %>