config/routes.rb
Rails.application.routes.draw do
  resources :ikeja_services

  resources :ikeja_patients

  resources :nationalities

  resources :religions

  resources :occupations

  resources :lgas

  resources :states

  resources :branches

  get 'pages/index'

  root 'pages#index'
end

app/models/branch.rb
class Branch < ActiveRecord::Base
	validates :name, :address, :prefix, :suffix, presence: true
	validates :name, :address, uniqueness: true
	has_many :patients
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :services
end

app/models/ikeja_patient.rb
class IkejaPatient < ActiveRecord::Base
	acts_as :patient
end

app/models/ikeja_service.rb
class IkejaService < ActiveRecord::Base
	acts_as :service
end

app/models/lga.rb
class Lga < ActiveRecord::Base
  belongs_to :state
end

app/models/nationality.rb
class Nationality < ActiveRecord::Base
end

app/models/occupation.rb
class Occupation < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	after_create :set_mrn
	actable
	belongs_to :state
	belongs_to :branch
	belongs_to :lga
	belongs_to :religion
	belongs_to :occupation
	belongs_to :nationality
	Gender = %w(Female Male)
	validates :surname, :first_name, :address, :gender, :phone, :state, presence: true

	def set_mrn
		prefix = self.branch.prefix
		suffix = self.branch.suffix
		update_attribute(:mrn, "#{prefix}"+"#{self.id}"+"#{suffix}")
	end

	def fullName
		self.first_name+" "+self.middle_name+" "+self.surname
	end
end

app/models/religion.rb
class Religion < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
	actable
	validates :item, :amount, :category_id, presence: true
	validates :item, uniqueness: true
	belongs_to :category
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_branch, only: [:show, :edit, :update, :destroy]

  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.all
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
  end

  # GET /branches/new
  def new
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to @branch, notice: 'Branch was successfully created.' }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :new }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1
  # PATCH/PUT /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to @branch, notice: 'Branch was successfully updated.' }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.html { render :edit }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to branches_url, notice: 'Branch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_params
      params.require(:branch).permit(:name, :address, :prefix, :suffix)
    end
end

app/controllers/lgas_controller.rb
class LgasController < ApplicationController
  before_action :set_lga, only: [:show, :edit, :update, :destroy]

  # GET /lgas
  # GET /lgas.json
  def index
    @lgas = Lga.all
  end

  # GET /lgas/1
  # GET /lgas/1.json
  def show
  end

  # GET /lgas/new
  def new
    @lga = Lga.new
  end

  # GET /lgas/1/edit
  def edit
  end

  # POST /lgas
  # POST /lgas.json
  def create
    @lga = Lga.new(lga_params)

    respond_to do |format|
      if @lga.save
        format.html { redirect_to @lga, notice: 'Lga was successfully created.' }
        format.json { render :show, status: :created, location: @lga }
      else
        format.html { render :new }
        format.json { render json: @lga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lgas/1
  # PATCH/PUT /lgas/1.json
  def update
    respond_to do |format|
      if @lga.update(lga_params)
        format.html { redirect_to @lga, notice: 'Lga was successfully updated.' }
        format.json { render :show, status: :ok, location: @lga }
      else
        format.html { render :edit }
        format.json { render json: @lga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lgas/1
  # DELETE /lgas/1.json
  def destroy
    @lga.destroy
    respond_to do |format|
      format.html { redirect_to lgas_url, notice: 'Lga was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lga
      @lga = Lga.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lga_params
      params.require(:lga).permit(:name, :state_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/lgas_helper.rb
module LgasHelper
end

app/helpers/nationalities_helper.rb
module NationalitiesHelper
end

app/helpers/occupations_helper.rb
module OccupationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/religions_helper.rb
module ReligionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/branches/_form.html.erb
<%= form_for(@branch) do |f| %>
  <% if @branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@branch.errors.count, "error") %> prohibited this branch from being saved:</h2>

      <ul>
      <% @branch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :prefix %>
    <%= f.text_field :prefix, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :suffix %>
    <%= f.text_field :suffix, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/branches/edit.html.erb
<h1>Editing Branch</h1>

<%= render 'form' %>

<%= link_to 'Show', @branch %> |
<%= link_to 'Back', branches_path %>

app/views/branches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Branches</h1>

<table class="table table hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Prefix</th>
      <th>Suffix</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @branches.each do |branch| %>
      <tr>
        <td><%= branch.name %></td>
        <td><%= branch.address %></td>
        <td><%= branch.prefix %></td>
        <td><%= branch.suffix %></td>
        <td><%= link_to 'Show', branch %></td>
        <td><%= link_to 'Edit', edit_branch_path(branch) %></td>
        <td><%= link_to 'Destroy', branch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Branch', new_branch_path %>

app/views/branches/new.html.erb
<h1>New Branch</h1>

<%= render 'form' %>

<%= link_to 'Back', branches_path %>

app/views/branches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @branch.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @branch.address %>
</p>

<p>
  <strong>Prefix:</strong>
  <%= @branch.prefix %>
</p>

<p>
  <strong>Suffix:</strong>
  <%= @branch.suffix %>
</p>

<%= link_to 'Edit', edit_branch_path(@branch) %> |
<%= link_to 'Back', branches_path %>