config/routes.rb
Rails.application.routes.draw do
  resources :ikeja_services

  resources :ikeja_patients

  resources :nationalities

  resources :religions

  resources :occupations

  resources :lgas

  resources :states

  resources :branches

  get 'pages/index'

  root 'pages#index'
end

app/models/branch.rb
class Branch < ActiveRecord::Base
	validates :name, :address, :prefix, :suffix, presence: true
	validates :name, :address, uniqueness: true
	has_many :patients
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :services
end

app/models/ikeja_patient.rb
class IkejaPatient < ActiveRecord::Base
	acts_as :patient
end

app/models/ikeja_service.rb
class IkejaService < ActiveRecord::Base
	acts_as :service
end

app/models/lga.rb
class Lga < ActiveRecord::Base
  belongs_to :state
end

app/models/nationality.rb
class Nationality < ActiveRecord::Base
end

app/models/occupation.rb
class Occupation < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	after_create :set_mrn
	actable
	belongs_to :state
	belongs_to :branch
	belongs_to :lga
	belongs_to :religion
	belongs_to :occupation
	belongs_to :nationality
	Gender = %w(Female Male)
	validates :surname, :first_name, :address, :gender, :phone, :state, presence: true

	def set_mrn
		prefix = self.branch.prefix
		suffix = self.branch.suffix
		update_attribute(:mrn, "#{prefix}"+"#{self.id}"+"#{suffix}")
	end

	def fullName
		self.first_name+" "+self.middle_name+" "+self.surname
	end
end

app/models/religion.rb
class Religion < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
	actable
	validates :item, :amount, :category_id, presence: true
	validates :item, uniqueness: true
	belongs_to :category
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/controllers/ikeja_services_controller.rb
class IkejaServicesController < ApplicationController
  before_action :set_ikeja_service, only: [:show, :edit, :update, :destroy]

  # GET /ikeja_services
  # GET /ikeja_services.json
  def index
    @ikeja_services = IkejaService.all
  end

  # GET /ikeja_services/1
  # GET /ikeja_services/1.json
  def show
  end

  # GET /ikeja_services/new
  def new
    @ikeja_service = IkejaService.new
  end

  # GET /ikeja_services/1/edit
  def edit
  end

  # POST /ikeja_services
  # POST /ikeja_services.json
  def create
    @ikeja_service = IkejaService.new(ikeja_service_params)

    respond_to do |format|
      if @ikeja_service.save
        format.html { redirect_to ikeja_services_path, notice: 'Ikeja service was successfully created.' }
        format.json { render :index, status: :created, location: ikeja_services_path }
      else
        format.html { render :new }
        format.json { render json: @ikeja_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ikeja_services/1
  # PATCH/PUT /ikeja_services/1.json
  def update
    respond_to do |format|
      if @ikeja_service.update(ikeja_service_params)
        format.html { redirect_to ikeja_services_path, notice: 'Ikeja service was successfully updated.' }
        format.json { render :index, status: :ok, location: ikeja_services_path }
      else
        format.html { render :edit }
        format.json { render json: @ikeja_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ikeja_services/1
  # DELETE /ikeja_services/1.json
  def destroy
    @ikeja_service.destroy
    respond_to do |format|
      format.html { redirect_to ikeja_services_url, notice: 'Ikeja service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ikeja_service
      @ikeja_service = IkejaService.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ikeja_service_params
      params.require(:ikeja_service).permit(:item, :amount, :category_id)
    end
end

app/controllers/lgas_controller.rb
class LgasController < ApplicationController
  before_action :set_lga, only: [:show, :edit, :update, :destroy]

  # GET /lgas
  # GET /lgas.json
  def index
    @lgas = Lga.all
  end

  # GET /lgas/1
  # GET /lgas/1.json
  def show
  end

  # GET /lgas/new
  def new
    @lga = Lga.new
  end

  # GET /lgas/1/edit
  def edit
  end

  # POST /lgas
  # POST /lgas.json
  def create
    @lga = Lga.new(lga_params)

    respond_to do |format|
      if @lga.save
        format.html { redirect_to @lga, notice: 'Lga was successfully created.' }
        format.json { render :show, status: :created, location: @lga }
      else
        format.html { render :new }
        format.json { render json: @lga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lgas/1
  # PATCH/PUT /lgas/1.json
  def update
    respond_to do |format|
      if @lga.update(lga_params)
        format.html { redirect_to @lga, notice: 'Lga was successfully updated.' }
        format.json { render :show, status: :ok, location: @lga }
      else
        format.html { render :edit }
        format.json { render json: @lga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lgas/1
  # DELETE /lgas/1.json
  def destroy
    @lga.destroy
    respond_to do |format|
      format.html { redirect_to lgas_url, notice: 'Lga was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lga
      @lga = Lga.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lga_params
      params.require(:lga).permit(:name, :state_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/ikeja_services_helper.rb
module IkejaServicesHelper
end

app/helpers/lgas_helper.rb
module LgasHelper
end

app/helpers/nationalities_helper.rb
module NationalitiesHelper
end

app/helpers/occupations_helper.rb
module OccupationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/religions_helper.rb
module ReligionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/ikeja_services/_form.html.erb
<%= form_for(@ikeja_service) do |f| %>
  <% if @ikeja_service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ikeja_service.errors.count, "error") %> prohibited this ikeja_service from being saved:</h2>

      <ul>
      <% @ikeja_service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.text_field :item, placeholder: "Item", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :amount, placeholder: "Amount", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Select Category"}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/ikeja_services/edit.html.erb
<h1>Editing Ikeja Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @ikeja_service %> |
<%= link_to 'Back', ikeja_services_path %>

app/views/ikeja_services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ikeja Services</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Item</th>
      <th>Amount (=N=)</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ikeja_services.each do |ikeja_service| %>
      <tr>
        <td><%= ikeja_service.item %></td>
        <td><%= ikeja_service.amount %></td>
        <td><%= ikeja_service.category.name %></td>
        <td><%= link_to 'Show', ikeja_service %></td>
        <td><%= link_to 'Edit', edit_ikeja_service_path(ikeja_service) %></td>
        <td><%= link_to 'Destroy', ikeja_service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ikeja service', new_ikeja_service_path %>

app/views/ikeja_services/new.html.erb
<h1>New Ikeja Service</h1>

<%= render 'form' %>

<%= link_to 'Back', ikeja_services_path %>

app/views/ikeja_services/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ikeja_service_path(@ikeja_service) %> |
<%= link_to 'Back', ikeja_services_path %>