config/routes.rb
Rails.application.routes.draw do
  resources :ikeja_services

  resources :ikeja_patients

  resources :nationalities

  resources :religions

  resources :occupations

  resources :lgas

  resources :states

  resources :branches

  get 'pages/index'

  root 'pages#index'
end

app/models/branch.rb
class Branch < ActiveRecord::Base
	validates :name, :address, :prefix, :suffix, presence: true
	validates :name, :address, uniqueness: true
	has_many :patients
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :services
end

app/models/ikeja_patient.rb
class IkejaPatient < ActiveRecord::Base
	acts_as :patient
end

app/models/ikeja_service.rb
class IkejaService < ActiveRecord::Base
	acts_as :service
end

app/models/lga.rb
class Lga < ActiveRecord::Base
  belongs_to :state
end

app/models/nationality.rb
class Nationality < ActiveRecord::Base
end

app/models/occupation.rb
class Occupation < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	after_create :set_mrn
	actable
	belongs_to :state
	belongs_to :branch
	belongs_to :lga
	belongs_to :religion
	belongs_to :occupation
	belongs_to :nationality
	Gender = %w(Female Male)
	validates :surname, :first_name, :address, :gender, :phone, :state, presence: true

	def set_mrn
		prefix = self.branch.prefix
		suffix = self.branch.suffix
		update_attribute(:mrn, "#{prefix}"+"#{self.id}"+"#{suffix}")
	end

	def fullName
		self.first_name+" "+self.middle_name+" "+self.surname
	end
end

app/models/religion.rb
class Religion < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
	actable
	validates :item, :amount, :category_id, presence: true
	validates :item, uniqueness: true
	belongs_to :category
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/controllers/lgas_controller.rb
class LgasController < ApplicationController
  before_action :set_lga, only: [:show, :edit, :update, :destroy]

  # GET /lgas
  # GET /lgas.json
  def index
    @lgas = Lga.all
  end

  # GET /lgas/1
  # GET /lgas/1.json
  def show
  end

  # GET /lgas/new
  def new
    @lga = Lga.new
  end

  # GET /lgas/1/edit
  def edit
  end

  # POST /lgas
  # POST /lgas.json
  def create
    @lga = Lga.new(lga_params)

    respond_to do |format|
      if @lga.save
        format.html { redirect_to @lga, notice: 'Lga was successfully created.' }
        format.json { render :show, status: :created, location: @lga }
      else
        format.html { render :new }
        format.json { render json: @lga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lgas/1
  # PATCH/PUT /lgas/1.json
  def update
    respond_to do |format|
      if @lga.update(lga_params)
        format.html { redirect_to @lga, notice: 'Lga was successfully updated.' }
        format.json { render :show, status: :ok, location: @lga }
      else
        format.html { render :edit }
        format.json { render json: @lga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lgas/1
  # DELETE /lgas/1.json
  def destroy
    @lga.destroy
    respond_to do |format|
      format.html { redirect_to lgas_url, notice: 'Lga was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lga
      @lga = Lga.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lga_params
      params.require(:lga).permit(:name, :state_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/ikeja_patients_helper.rb
module IkejaPatientsHelper
end

app/helpers/lgas_helper.rb
module LgasHelper
end

app/helpers/nationalities_helper.rb
module NationalitiesHelper
end

app/helpers/occupations_helper.rb
module OccupationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/religions_helper.rb
module ReligionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/lgas/_form.html.erb
<%= form_for(@lga) do |f| %>
  <% if @lga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lga.errors.count, "error") %> prohibited this lga from being saved:</h2>

      <ul>
      <% @lga.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :state_id %><br>
    <%= f.text_field :state_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lgas/edit.html.erb
<h1>Editing Lga</h1>

<%= render 'form' %>

<%= link_to 'Show', @lga %> |
<%= link_to 'Back', lgas_path %>

app/views/lgas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lgas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lgas.each do |lga| %>
      <tr>
        <td><%= lga.name %></td>
        <td><%= lga.state %></td>
        <td><%= link_to 'Show', lga %></td>
        <td><%= link_to 'Edit', edit_lga_path(lga) %></td>
        <td><%= link_to 'Destroy', lga, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lga', new_lga_path %>

app/views/lgas/new.html.erb
<h1>New Lga</h1>

<%= render 'form' %>

<%= link_to 'Back', lgas_path %>

app/views/lgas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lga.name %>
</p>

<p>
  <strong>State:</strong>
  <%= @lga.state %>
</p>

<%= link_to 'Edit', edit_lga_path(@lga) %> |
<%= link_to 'Back', lgas_path %>

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing States</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.name %></td>
        <td><%= link_to 'Show', state %></td>
        <td><%= link_to 'Edit', edit_state_path(state) %></td>
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New State</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>